"""empty message

Revision ID: 6bd9af140db6
Revises: bb3508336cc0
Create Date: 2021-08-29 12:02:40.969391

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bd9af140db6'
down_revision = 'bb3508336cc0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('favorite', sa.Column('planet_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'favorite', 'planet', ['planet_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'favorite', type_='foreignkey')
    op.drop_column('favorite', 'planet_id')
    # ### end Alembic commands ###
